apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: type
            operator: In
            values:
            - high-performance
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
