apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rolling
spec:
  replicas: 10
  minReadySeconds: 10
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 4
      maxSurge: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: hkshitesh/kubedemo:2.0
        ports:
        - containerPort: 80
