apiVersion: v1
kind: Pod
metadata:
  name: simple-multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alpine-container
    image: alpine
    command: ["sh", "-c", "while true; do echo Hello from Alpine; sleep 10; done"]
